using Avenga.DataAnnotations.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Avenga.DataAnnotations.Domain.Models
{
    [Table("Notes")] // The corresponding table in the database will be named "Notes"
    public class Note
    {
        [Key] // This attribute indicates that this property is the primary key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // This attribute indicates that the value is generated by the database
        public int Id { get; set; }
        [Required] // This attribute indicates that this property is required not null
        [MaxLength(100)] // This attribute indicates that the maximum length of this string is 100 characters
        public string Text { get; set; }
        [Required] // This attribute indicates that this property is required not null
        public Priority Priority { get; set; }
        [Required] // This attribute indicates that this property is required not null
        public Tag Tag { get; set; }
        public int UserId { get; set; } 
        [ForeignKey("UserId")] // This attribute indicates that this property is a foreign key to the User table
        public User User { get; set; }
    }
}
