using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Avenga.DataAnnotations.Domain.Models
{
    [Table("Users")] // The corresponding table in the database will be named "Users"
    public class User
    {
        [Key] // This attribute indicates that this property is the primary key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // This attribute indicates that the value is generated by the database
        public int Id { get; set; }
        [MaxLength(50)] // This attribute indicates that the maximum length of this string is 50 characters
        public string? FirstName { get; set; }
        [MaxLength(50)] // This attribute indicates that the maximum length of this string is 50 characters
        public string? LastName { get; set; }
        [Required] // This attribute indicates that this property is required not null
        [MaxLength(30)] // This attribute indicates that the maximum length of this string is 30 characters
        public string Username { get; set; }
        [InverseProperty("User")] // This means that this collection is corresponding to the User navigational property in the Note class/table
        public List<Note> Notes { get; set; }
    }
}
